### ISSUE TITLE
Disable Submit Button while Form Invalid

### ISSUE THREAD

**Issue by mcgear** [dschnelldavis/angular2-json-schema-form#77]
Not sure if it is a bug, so much as feature request.  I'd like to see the submit button disabled when the form is invalid.  I see where the submit widget does support a controlDisabled property that is set in the JsonSchemaFormService to the value of the ctx.formControl.disabled.  

Would be nice if i could do something like in the feedback node of the layout options where we could specify an angular string:

...
disabled: "hasError()"

Or if that was the default behavior since it is expected in the case of invalid form.

I forked the code and was thinking i'd see what i can see, but am getting the error provided below.  So can't go much farther.

C:\Git\Public\angular2-json-schema-form>node build.js
Inlining succeeded.
ES2015 compilation succeeded.
ES5 compilation succeeded.
Typings and metadata copy succeeded.
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Build failed. See below for errors.

Error: Multiple conflicting contents for sourcemap source undefined
    at error (C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:177:12)
    at C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:9441:6
    at Array.forEach (native)
    at C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:9415:8
    at Array.map (native)
    at Link.traceMappings (C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:9412:31)
    at collapseSourcemaps (C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:9544:19)
    at Bundle.render (C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:10157:10)
    at generate (C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:10367:27)
    at Object.write (C:\Fifty280\Git\Public\angular2-json-schema-form\node_modules\rollup\dist\rollup.js:10399:19)

Any thoughts on getting past that, or squeezing in a solution would be great!  Thanks for the help

**Comment by dschnelldavis** [comment]
Yep, this is a good idea. I'll add it soon.

**Comment by mcgear** [comment]
thx
