### ISSUE TITLE
Cannot build (on MacOS)

### ISSUE THREAD

**Issue by pgp44** [dschnelldavis/angular2-json-schema-form#82]
Hello

I am trying to follow the "installation" procedure 

git clone ..
cd ...
npm install

While doing, I run into the following (on npm install)

Using node v8.4.0 and npm 5.30 (I tried earlier version but got the same issue)

```
Inlining succeeded.
ES2015 compilation succeeded.
ES5 compilation succeeded.
Typings and metadata copy succeeded.
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
Build failed. See below for errors.

Error: Could not resolve '@angular/cdk/a11y' from /Users/peter/playground/angular2-json-schema-form/node_modules/@angular/material/@angular/material.es5.js
    at /Users/peter/playground/angular2-json-schema-form/node_modules/rollup-plugin-node-resolve-angular/dist/rollup-plugin-node-resolve.cjs.js:92:23
    at /Users/peter/playground/angular2-json-schema-form/node_modules/resolve/lib/async.js:50:13
    at processDirs (/Users/peter/playground/angular2-json-schema-form/node_modules/resolve/lib/async.js:182:39)
    at ondir (/Users/peter/playground/angular2-json-schema-form/node_modules/resolve/lib/async.js:197:13)
    at load (/Users/peter/playground/angular2-json-schema-form/node_modules/resolve/lib/async.js:80:43)
    at onex (/Users/peter/playground/angular2-json-schema-form/node_modules/resolve/lib/async.js:105:17)
    at /Users/peter/playground/angular2-json-schema-form/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:152:21)
```

Full log attached

Any suggestions what I am doing wrong?

Tx!

Peter

[2017-09-03T10_21_47_547Z-debug.log.zip](https://github.com/dschnelldavis/angular2-json-schema-form/files/1272846/2017-09-03T10_21_47_547Z-debug.log.zip)

**Comment by pgp44** [comment]
When I install @angular/cdk, the compilation continues. 

After that, doing npm start gives warnings. 
```
WARNING in Circular dependency detected:
src/lib/src/framework-library/framework-library.module.ts -> src/lib/src/framework-library/index.ts -> src/lib/src/framework-library/framework-library.module.ts

WARNING in Circular dependency detected:
src/lib/src/framework-library/index.ts -> src/lib/src/framework-library/framework-library.module.ts -> src/lib/src/framework-library/index.ts

WARNING in Circular dependency detected:
src/lib/src/widget-library/index.ts -> src/lib/src/widget-library/widget-library.module.ts -> src/lib/src/widget-library/index.ts

WARNING in Circular dependency detected:
src/lib/src/widget-library/widget-library.module.ts -> src/lib/src/widget-library/index.ts -> src/lib/src/widget-library/widget-library.module.ts


```
And the browser stops on "Loading" on http://localhost:4200

**Comment by dschnelldavis** [comment]
Hmmm. I do all the primary development for this library on a Mac (OS 10.2, Node 6.9.5, NPM 5.4.2), so it should build fine. I even updated my Node to 8.5.0, and that works too.

I have fixed some other issues with required modules recently though—so it's possible one of those updates also fixed this issue.

Pleas try it again with the latest version, and let me know if it works.

Thanks!
